export const ARCHIVE_VERSE_PENDING = 'ARCHIVE_VERSE_PENDING';
export const ARCHIVE_VERSE_SUCCESS = 'ARCHIVE_VERSE_SUCCESS';
export const ARCHIVE_VERSE_FAILED = 'ARCHIVE_VERSE_FAILED';
export const SAVE_AS_FAVORITE = 'SAVE_AS_FAVORITE';
export const REMOVE_AS_FAVORITE = 'REMOVE_AS_FAVORITE';
