export const GET_BIBLES_PENDING = 'GET_BIBLES_PENDING';
export const GET_BIBLES_SUCCESS = 'GET_BIBLES_SUCCESS';
export const GET_BIBLES_FAILED = 'GET_BIBLES_FAILED';
export const SET_BIBLE = 'SET_BIBLE';
