export const GET_CHAPTERS_PENDING = 'GET_CHAPTERS_PENDING';
export const GET_CHAPTERS_SUCCESS = 'GET_CHAPTERS_SUCCESS';
export const GET_CHAPTERS_FAILED = 'GET_CHAPTERS_FAILED';
export const SET_CHAPTER = 'SET_CHAPTER';
