export const GET_VERSES_PENDING = 'GET_VERSES_PENDING';
export const GET_VERSES_SUCCESS = 'GET_VERSES_SUCCESS';
export const GET_VERSES_FAILED = 'GET_VERSES_FAILED';
export const CLEAR_VERSES = 'CLEAR_VERSES';
export const SET_VERSE = 'SET_VERSE';
